version: '3.7'

services:

  tf-serving-server:
    container_name: tf-serving-server
    image: tensorflow/serving
    command: --model_base_path=/models/covid --model_name==covid 
    volumes:
      - ./tmp/:/models/covid
    networks:
      - tf_serving
    ports:
      - "8500:8500"
      - "8501:8501"

  flask_server:
    container_name: flask_server
    restart: always
    build:
        context: ./flask_server
        dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000"  
    networks:
      - tf_serving
    depends_on:
      - tf-serving-server

networks:
  tf_serving:
    driver: bridge